import { Clock, Moon, Sun, BookOpen, Heart, Settings } from 'lucide-react';
import AZKAR_DATA from '../data/azkar-data.js';

// ═══════════════════════════════════════════
// Re-export azkar data
// ═══════════════════════════════════════════
export const { azkar, defaultCustomDuas, tabs: tabConfig } = AZKAR_DATA;

// Icon map — used by AzkarApp to resolve tab icons from string keys
export const ICONS = { Clock, Moon, Sun, BookOpen, Heart, Settings };

// ═══════════════════════════════════════════
// Prayer Banners for next prayer display
// ═══════════════════════════════════════════
export const PRAYER_BANNERS = [
    { key: "Fajr",    ar: "الفجر",   en: "Fajr",    icon: "🌅" },
    { key: "Dhuhr",   ar: "الظهر",   en: "Dhuhr",   icon: "🌞" },
    { key: "Asr",     ar: "العصر",   en: "Asr",     icon: "🌤️" },
    { key: "Maghrib", ar: "المغرب",  en: "Maghrib", icon: "🌆" },
    { key: "Isha",    ar: "العشاء",  en: "Isha",    icon: "🌙" }
];

// Tabs that show daily progress (azkar lists)
export const DAILY_TAB_IDS = ["morning", "evening", "sleeping", "prayer_azkar", "jawami"];

// Fallback prayer times when offline
export const OFFLINE_PRAYER_TIMES = {
    Fajr: "04:45", Sunrise: "06:15", Dhuhr: "11:50",
    Asr: "15:10", Maghrib: "17:30", Isha: "19:00"
};

// Prayer checklist items
export const PRAYER_CHECKLIST = [
    { id: "fajr",    ar: "الفجر",   en: "Fajr" },
    { id: "dhuhr",   ar: "الظهر",   en: "Dhuhr" },
    { id: "asr",     ar: "العصر",   en: "Asr" },
    { id: "maghrib", ar: "المغرب",  en: "Maghrib" },
    { id: "isha",    ar: "العشاء",  en: "Isha" }
];

// ═══════════════════════════════════════════
// Accent Color Options - Single source of truth
// ═══════════════════════════════════════════
export const ACCENT_OPTIONS = [
    { id: "indigo", labelAr: "أزرق ملكي", labelEn: "Indigo", vars: { '--primary': '#6366f1', '--primary-light': '#818cf8', '--primary-dark': '#4f46e5', '--accent': '#f59e0b', '--accent-light': '#fbbf24', '--accent-dark': '#d97706', '--accent-glow': 'rgba(245, 158, 11, 0.25)', '--primary-rgb': '99,102,241', '--accent-rgb': '245,158,11' }, darkVars: { '--primary': '#818cf8', '--primary-light': '#a5b4fc', '--primary-dark': '#6366f1', '--accent': '#fbbf24', '--accent-light': '#fcd34d', '--accent-dark': '#f59e0b', '--accent-glow': 'rgba(251, 191, 36, 0.25)', '--primary-rgb': '129,140,248', '--accent-rgb': '251,191,36' } },
    { id: "emerald", labelAr: "أخضر زمردي", labelEn: "Emerald", vars: { '--primary': '#10b981', '--primary-light': '#34d399', '--primary-dark': '#059669', '--accent': '#14b8a6', '--accent-light': '#2dd4bf', '--accent-dark': '#0f766e', '--accent-glow': 'rgba(20, 184, 166, 0.25)', '--primary-rgb': '16,185,129', '--accent-rgb': '20,184,166' }, darkVars: { '--primary': '#34d399', '--primary-light': '#6ee7b7', '--primary-dark': '#10b981', '--accent': '#2dd4bf', '--accent-light': '#5eead4', '--accent-dark': '#14b8a6', '--accent-glow': 'rgba(45, 212, 191, 0.25)', '--primary-rgb': '52,211,153', '--accent-rgb': '45,212,191' } },
    { id: "rose", labelAr: "وردي ناعم", labelEn: "Rose", vars: { '--primary': '#ec4899', '--primary-light': '#f472b6', '--primary-dark': '#be185d', '--accent': '#f97316', '--accent-light': '#fb923c', '--accent-dark': '#ea580c', '--accent-glow': 'rgba(236, 72, 153, 0.2)', '--primary-rgb': '236,72,153', '--accent-rgb': '249,115,22' }, darkVars: { '--primary': '#f472b6', '--primary-light': '#fbcfe8', '--primary-dark': '#ec4899', '--accent': '#fb923c', '--accent-light': '#fdba74', '--accent-dark': '#f97316', '--accent-glow': 'rgba(251, 146, 60, 0.25)', '--primary-rgb': '244,114,182', '--accent-rgb': '251,146,60' } },
    { id: "teal", labelAr: "أخضر بحري", labelEn: "Teal", vars: { '--primary': '#14b8a6', '--primary-light': '#2dd4bf', '--primary-dark': '#0f766e', '--accent': '#22d3ee', '--accent-light': '#67e8f9', '--accent-dark': '#0e7490', '--accent-glow': 'rgba(20, 184, 166, 0.25)', '--primary-rgb': '20,184,166', '--accent-rgb': '34,211,238' }, darkVars: { '--primary': '#2dd4bf', '--primary-light': '#5eead4', '--primary-dark': '#14b8a6', '--accent': '#67e8f9', '--accent-light': '#a5f3fc', '--accent-dark': '#22d3ee', '--accent-glow': 'rgba(103, 232, 249, 0.25)', '--primary-rgb': '45,212,191', '--accent-rgb': '103,232,249' } },
    { id: "blue", labelAr: "أزرق كحلي", labelEn: "Blue", vars: { '--primary': '#3b82f6', '--primary-light': '#60a5fa', '--primary-dark': '#2563eb', '--accent': '#8b5cf6', '--accent-light': '#a78bfa', '--accent-dark': '#7c3aed', '--accent-glow': 'rgba(59, 130, 246, 0.25)', '--primary-rgb': '59,130,246', '--accent-rgb': '139,92,246' }, darkVars: { '--primary': '#60a5fa', '--primary-light': '#93c5fd', '--primary-dark': '#3b82f6', '--accent': '#a78bfa', '--accent-light': '#c4b5fd', '--accent-dark': '#8b5cf6', '--accent-glow': 'rgba(96, 165, 250, 0.25)', '--primary-rgb': '96,165,250', '--accent-rgb': '167,139,250' } },
    { id: "purple", labelAr: "بنفسجي", labelEn: "Purple", vars: { '--primary': '#a855f7', '--primary-light': '#c084fc', '--primary-dark': '#9333ea', '--accent': '#ec4899', '--accent-light': '#f472b6', '--accent-dark': '#db2777', '--accent-glow': 'rgba(168, 85, 247, 0.25)', '--primary-rgb': '168,85,247', '--accent-rgb': '236,72,153' }, darkVars: { '--primary': '#c084fc', '--primary-light': '#e9d5ff', '--primary-dark': '#a855f7', '--accent': '#f472b6', '--accent-light': '#fda5d5', '--accent-dark': '#ec4899', '--accent-glow': 'rgba(192, 132, 252, 0.25)', '--primary-rgb': '192,132,252', '--accent-rgb': '244,114,182' } },
    { id: "amber", labelAr: "عنابي", labelEn: "Amber", vars: { '--primary': '#f59e0b', '--primary-light': '#fbbf24', '--primary-dark': '#d97706', '--accent': '#ef4444', '--accent-light': '#f87171', '--accent-dark': '#dc2626', '--accent-glow': 'rgba(245, 158, 11, 0.25)', '--primary-rgb': '245,158,11', '--accent-rgb': '239,68,68' }, darkVars: { '--primary': '#fbbf24', '--primary-light': '#fde68a', '--primary-dark': '#f59e0b', '--accent': '#f87171', '--accent-light': '#fca5a5', '--accent-dark': '#ef4444', '--accent-glow': 'rgba(251, 191, 36, 0.25)', '--primary-rgb': '251,191,36', '--accent-rgb': '248,113,113' } }
];

// ═══════════════════════════════════════════
// Internationalization
// ═══════════════════════════════════════════
export const I18N = {
    ar: {
        appName: "حصنك",
        appTagline: "الحِصن المنيع للمسلم",
        loginTitle: "تسجيل الدخول",
        loginSubtitle: "احفظ بياناتك وتقدمك على هذا الجهاز",
        createAccountTitle: "إنشاء حساب جديد",
        createAccountSubtitle: "أنشئ ملفك المحلي وابدأ بحفظ تقدمك على هذا الجهاز",
        nameLabel: "الاسم الكامل",
        emailLabel: "البريد الإلكتروني",
        loginButton: "دخول",
        createAccountButton: "إنشاء حساب",
        createAccountLink: "إنشاء حساب جديد",
        signInInstead: "لديك حساب بالفعل",
        existingAccountsTitle: "الحسابات المحفوظة",
        signInAs: "تسجيل الدخول باسم",
        settingsHint: "ستجد الإعدادات من زر الترس أعلى الشاشة بعد الدخول.",
        openSettings: "الإعدادات",
        logoutButton: "تسجيل الخروج",
        settingsTitle: "الإعدادات",
        languageTitle: "اللغة",
        languageAr: "العربية",
        languageEn: "English",
        streakTitle: "سلسلة الإنجاز",
        progressLabel: "التقدم",
        streakSubtitle: "حافظ على إنجاز الأذكار والصلوات اليومية",
        streakDays: "أيام متتالية",
        goalsTitle: "أهداف اليوم",
        goalMorning: "أذكار الصباح",
        goalEvening: "أذكار المساء",
        goalPrayers: "الصلوات الخمس",
        prayerChecklistTitle: "تسجيل الصلوات",
        prayerChecklistNote: "علّم كل صلاة عند انتهائها",
        profileTitle: "الملف الشخصي",
        profileNote: "بياناتك محفوظة محلياً على هذا الجهاز",
        updateProfile: "تحديث البيانات",
        loginSaved: "تم حفظ بياناتك",
        accountCreated: "تم إنشاء الحساب بنجاح",
        signedIn: "تم تسجيل الدخول بناح",
        wrongPassword: "كلمة المرور غير صحيحة، حاول مرة أخرى",
        userNotFound: "لم يتم العثور على حساب بهذا البريد",
        userExists: "يوجد حساب بهذا البريد بالفعل",
        loggedOut: "تم تسجيل الخروج",
        loginRequired: "الرجاء تسجيل الدخول للمتابعة",
        duaAdded: "تمت إضافة الدعاء بنجاح",
        duaDeleted: "تم حذف الدعاء",
        pwaInstall: "تم البدء في تثبيت التطبيق",
        progressTitleMorning: "☀️ أذكار الصباح",
        progressTitleEvening: "🌙 أذكار المساء",
        progressTitleSleeping: "🌌 أذكار النوم",
        progressTitlePrayer: "🕌 أذكار بعد الصلاة",
        progressText: "تم إنجاز",
        progressOf: "من",
        progressAzkar: "أذكار",
        resetProgress: "إعادة تعيين",
        prayerTimesTitle: "🕌 مواقيت الصلاة",
        prayerTimesLoading: "جاري تحميل المواقيت...",
        customTitle: "أدعيتك الخاصة",
        customSubtitle: "أضف أدعيتك المفضلة هنا واحتفظ بها دائماً",
        customPlaceholder: "اكتب دعاءً جديداً...",
        addDua: "إضافة دعاء",
        noDuas: "لا توجد أدعية بعد",
        noDuasHint: "أضف أدعيتك المفضلة عبر الحقل أعلاه",
        locationTitle: "الموقع الافتراضي",
        cityLabel: "المدينة",
        countryLabel: "كود الدولة",
        appearanceTitle: "المظهر",
        darkOn: "الوضع الداكن مُفعّل",
        lightOn: "الوضع الفاتح مُفعّل",
        aboutTitle: "حول التطبيق",
        offline: "غير متصل",
        online: "متصل",
        offlineNotice: "أنت الآن بدون إنترنت — التطبيق يعمل بشكل طبيعي",
        onlineNotice: "تم إعادة الاتصال بالإنترنت",
        shareCopy: "تم نسخ الذكر",
        shareTitle: "مشاركة",
        shareLabel: "مشاركة الذكر",
        markComplete: "تحديد كمكتمل",
        markPrayer: "علّم الصلاة",
        resetCounter: "إعادة تعيين",
        doneLabel: "تم ✓",
        requiredLabel: "المطلوب",
        benefitShow: "عرض الفضل والمصدر",
        benefitHide: "إخفاء الفضل والمصدر",
        deleteDua: "حذف الدعاء",
        scrollTopLabel: "العودة للأعلى",
        navLabel: "القائمة الرئيسية",
        resetAllLabel: "إعادة تعيين جميع الأذكار",
        resetAllToast: "تم إعادة تعيين جميع الأذكار",
        progressResetOne: "تم إعادة تعيين العداد",
        progressCompleted: "تم إتمام الذكر ✓",
        meaningTitle: "شرح ومعاني الكلمات",
        allComplete: "🎉 تم إتمام القسم!",
        welcomeMessage: "مرحباً {name}! استعد لتقوية حصنك اليوم.",
        notificationTitlePrayer: "تذكير الصلاة",
        notificationBodyPrayer: "يا {name}، حان وقت الصلاة الآن.",
        notificationTitleAzkar: "تذكير الأذكار",
        notificationBodyAzkar: "يا {name}، وقت الأذكار اليومية بدأ.",
        notificationsTitle: "الإشعارات",
        enableNotifications: "تفعيل الإشعارات",
        notificationsNote: "ستتلقى تذكيراً بمواقيت الصلاة والأذكار اليومية.",
        notificationSoundLabel: "نغمة التذكير",
        prayerNotificationLabel: "تذكير مواقيت الصلاة",
        azkarNotificationLabel: "تذكير الأذكار",
        colorThemeLabel: "لون التطبيق",
        goalCompleteMessage: "أشطر كتكوت!",
        passwordLabel: "كلمة المرور",
        passwordRequired: "كلمة المرور مطلوبة",
        passwordMinError: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
        passwordHint: "الحساب محفوظ محلياً على هذا الجهاز.",
        toggleEnTrans: "ترجمة الفوائد والمصادر",
        showArOriginal: "عرض الأصل العربي",
        jawamiTitle: "جوامع الدعاء",
        spaceHint: "اضغط Space للعد السريع"
    },
    en: {
        appName: "Hesnok",
        appTagline: "Your daily spiritual companion",
        loginTitle: "Sign In",
        loginSubtitle: "Save your info and progress on this device",
        createAccountTitle: "Create Account",
        createAccountSubtitle: "Create a local profile and keep your progress on this device",
        nameLabel: "Full name",
        emailLabel: "Email",
        loginButton: "Continue",
        createAccountButton: "Create account",
        createAccountLink: "Create a new account",
        signInInstead: "I already have an account",
        existingAccountsTitle: "Saved accounts",
        signInAs: "Sign in as",
        settingsHint: "You can find Settings from the gear button at the top after signing in.",
        openSettings: "Settings",
        logoutButton: "Sign out",
        settingsTitle: "Settings",
        languageTitle: "Language",
        languageAr: "العربية",
        languageEn: "English",
        streakTitle: "Streak",
        progressLabel: "Progress",
        streakSubtitle: "Keep up your daily azkar and prayers",
        streakDays: "days",
        goalsTitle: "Today's goals",
        goalMorning: "Morning azkar",
        goalEvening: "Evening azkar",
        goalPrayers: "Five prayers",
        prayerChecklistTitle: "Prayer checklist",
        prayerChecklistNote: "Mark each prayer when completed",
        profileTitle: "Profile",
        profileNote: "Your data is stored locally on this device",
        updateProfile: "Update profile",
        loginSaved: "Profile saved",
        accountCreated: "Account created successfully",
        signedIn: "Signed in successfully",
        wrongPassword: "Password is incorrect, please try again",
        userNotFound: "No account found for this email",
        userExists: "An account already exists with this email",
        loggedOut: "Signed out successfully",
        loginRequired: "Please sign in to continue",
        duaAdded: "Duaa added",
        duaDeleted: "Duaa deleted",
        pwaInstall: "App installation started",
        progressTitleMorning: "☀️ Morning Azkar",
        progressTitleEvening: "🌙 Evening Azkar",
        progressTitleSleeping: "🌌 Sleeping Azkar",
        progressTitlePrayer: "🕌 After Prayer Azkar",
        progressText: "Completed",
        progressOf: "of",
        progressAzkar: "azkar",
        resetProgress: "Reset",
        prayerTimesTitle: "🕌 Prayer Times",
        prayerTimesLoading: "Loading prayer times...",
        customTitle: "Your duaas",
        customSubtitle: "Add your favorite duaas and keep them here",
        customPlaceholder: "Type a new duaa...",
        addDua: "Add duaa",
        noDuas: "No duaas yet",
        noDuasHint: "Add your favorite duaas above",
        locationTitle: "Default location",
        cityLabel: "City",
        countryLabel: "Country code",
        appearanceTitle: "Appearance",
        darkOn: "Dark mode on",
        lightOn: "Light mode on",
        aboutTitle: "About",
        offline: "Offline",
        online: "Online",
        offlineNotice: "You are offline — the app still works",
        onlineNotice: "Back online",
        shareCopy: "Copied",
        shareTitle: "Share",
        shareLabel: "Share azkar",
        markComplete: "Mark complete",
        markPrayer: "Mark prayer",
        resetCounter: "Reset",
        doneLabel: "Done",
        requiredLabel: "Required",
        benefitShow: "Show benefit and source",
        benefitHide: "Hide benefit and source",
        deleteDua: "Delete duaa",
        scrollTopLabel: "Back to top",
        navLabel: "Main navigation",
        resetAllLabel: "Reset all azkar",
        resetAllToast: "All azkar reset",
        progressResetOne: "Counter reset",
        progressCompleted: "Marked complete",
        meaningTitle: "Meaning and Explanation",
        welcomeMessage: "Welcome back, {name}! Your fortress is ready.",
        notificationTitlePrayer: "Prayer reminder",
        notificationBodyPrayer: "{name}, it's prayer time now.",
        notificationTitleAzkar: "Azkar reminder",
        notificationBodyAzkar: "{name}, your daily azkar time has started.",
        notificationsTitle: "Reminders",
        enableNotifications: "Enable Notifications",
        notificationsNote: "You'll receive reminders at prayer times and for daily azkar.",
        notificationSoundLabel: "Reminder sound",
        prayerNotificationLabel: "Prayer time reminders",
        azkarNotificationLabel: "Azkar reminders",
        colorThemeLabel: "App color",
        goalCompleteMessage: "You're the best little champion!",
        passwordLabel: "Password",
        passwordRequired: "Password is required",
        passwordMinError: "Password must be at least 6 characters",
        passwordHint: "Your account is stored locally on this device.",
        toggleEnTrans: "English Translation (Benefits)",
        showArOriginal: "Show Original Arabic",
        jawamiTitle: "Prophet's Duas",
        spaceHint: "Press Space to count quickly"
    }
};
