import { Clock, Moon, Sun, BookOpen, Heart, Settings } from 'lucide-react';
import AZKAR_DATA from '../data/azkar-data.js';

// ═══════════════════════════════════════════
// Re-export azkar data
// ═══════════════════════════════════════════
export const { azkar, defaultCustomDuas, tabs: tabConfig } = AZKAR_DATA;

// Icon map — used by AzkarApp to resolve tab icons from string keys
export const ICONS = { Clock, Moon, Sun, BookOpen, Heart, Settings };

// Tabs that show daily progress (azkar lists)
export const DAILY_TAB_IDS = ["morning", "evening", "sleeping", "prayer_azkar", "jawami"];

// Fallback prayer times when offline
export const OFFLINE_PRAYER_TIMES = {
    Fajr: "04:45", Sunrise: "06:15", Dhuhr: "11:50",
    Asr: "15:10", Maghrib: "17:30", Isha: "19:00"
};

// Prayer checklist items
export const PRAYER_CHECKLIST = [
    { id: "fajr",    ar: "الفجر",   en: "Fajr" },
    { id: "dhuhr",   ar: "الظهر",   en: "Dhuhr" },
    { id: "asr",     ar: "العصر",   en: "Asr" },
    { id: "maghrib", ar: "المغرب",  en: "Maghrib" },
    { id: "isha",    ar: "العشاء",  en: "Isha" }
];

// ═══════════════════════════════════════════
// Internationalization
// ═══════════════════════════════════════════
export const I18N = {
    ar: {
        appName: "حصنك",
        appTagline: "الحِصن المنيع للمسلم",
        loginTitle: "تسجيل الدخول",
        loginSubtitle: "احفظ بياناتك وتقدمك على هذا الجهاز",
        createAccountTitle: "إنشاء حساب جديد",
        createAccountSubtitle: "أنشئ ملفك المحلي وابدأ بحفظ تقدمك على هذا الجهاز",
        nameLabel: "الاسم الكامل",
        emailLabel: "البريد الإلكتروني",
        loginButton: "دخول",
        createAccountButton: "إنشاء حساب",
        createAccountLink: "إنشاء حساب جديد",
        signInInstead: "لديك حساب بالفعل",
        settingsHint: "ستجد الإعدادات من زر الترس أعلى الشاشة بعد الدخول.",
        openSettings: "الإعدادات",
        logoutButton: "تسجيل الخروج",
        settingsTitle: "الإعدادات",
        languageTitle: "اللغة",
        languageAr: "العربية",
        languageEn: "English",
        streakTitle: "سلسلة الإنجاز",
        progressLabel: "التقدم",
        streakSubtitle: "حافظ على إنجاز الأذكار والصلوات اليومية",
        streakDays: "أيام متتالية",
        goalsTitle: "أهداف اليوم",
        goalMorning: "أذكار الصباح",
        goalEvening: "أذكار المساء",
        goalPrayers: "الصلوات الخمس",
        prayerChecklistTitle: "تسجيل الصلوات",
        prayerChecklistNote: "علّم كل صلاة عند انتهائها",
        profileTitle: "الملف الشخصي",
        profileNote: "بياناتك محفوظة محلياً على هذا الجهاز",
        updateProfile: "تحديث البيانات",
        loginSaved: "تم حفظ بياناتك",
        loginRequired: "الرجاء تسجيل الدخول للمتابعة",
        duaAdded: "تمت إضافة الدعاء بنجاح",
        duaDeleted: "تم حذف الدعاء",
        pwaInstall: "تم البدء في تثبيت التطبيق",
        progressTitleMorning: "☀️ أذكار الصباح",
        progressTitleEvening: "🌙 أذكار المساء",
        progressTitleSleeping: "🌌 أذكار النوم",
        progressTitlePrayer: "🕌 أذكار بعد الصلاة",
        progressText: "تم إنجاز",
        progressOf: "من",
        progressAzkar: "أذكار",
        resetProgress: "إعادة تعيين",
        prayerTimesTitle: "🕌 مواقيت الصلاة",
        prayerTimesLoading: "جاري تحميل المواقيت...",
        customTitle: "أدعيتك الخاصة",
        customSubtitle: "أضف أدعيتك المفضلة هنا واحتفظ بها دائماً",
        customPlaceholder: "اكتب دعاءً جديداً...",
        addDua: "إضافة دعاء",
        noDuas: "لا توجد أدعية بعد",
        noDuasHint: "أضف أدعيتك المفضلة عبر الحقل أعلاه",
        locationTitle: "الموقع الافتراضي",
        cityLabel: "المدينة",
        countryLabel: "كود الدولة",
        appearanceTitle: "المظهر",
        darkOn: "الوضع الداكن مُفعّل",
        lightOn: "الوضع الفاتح مُفعّل",
        aboutTitle: "حول التطبيق",
        offline: "غير متصل",
        online: "متصل",
        offlineNotice: "أنت الآن بدون إنترنت — التطبيق يعمل بشكل طبيعي",
        onlineNotice: "تم إعادة الاتصال بالإنترنت",
        shareCopy: "تم نسخ الذكر",
        shareTitle: "مشاركة",
        shareLabel: "مشاركة الذكر",
        markComplete: "تحديد كمكتمل",
        resetCounter: "إعادة تعيين",
        doneLabel: "تم ✓",
        requiredLabel: "المطلوب",
        benefitShow: "عرض الفضل والمصدر",
        benefitHide: "إخفاء الفضل والمصدر",
        deleteDua: "حذف الدعاء",
        scrollTopLabel: "العودة للأعلى",
        navLabel: "القائمة الرئيسية",
        resetAllLabel: "إعادة تعيين جميع الأذكار",
        resetAllToast: "تم إعادة تعيين جميع الأذكار",
        progressResetOne: "تم إعادة تعيين العداد",
        progressCompleted: "تم إتمام الذكر ✓",
        meaningTitle: "شرح ومعاني الكلمات",
        allComplete: "🎉 تم إتمام القسم!"
    },
    en: {
        appName: "Hesnok",
        appTagline: "Your daily spiritual companion",
        loginTitle: "Sign In",
        loginSubtitle: "Save your info and progress on this device",
        createAccountTitle: "Create Account",
        createAccountSubtitle: "Create a local profile and keep your progress on this device",
        nameLabel: "Full name",
        emailLabel: "Email",
        loginButton: "Continue",
        createAccountButton: "Create account",
        createAccountLink: "Create a new account",
        signInInstead: "I already have an account",
        settingsHint: "You can find Settings from the gear button at the top after signing in.",
        openSettings: "Settings",
        logoutButton: "Sign out",
        settingsTitle: "Settings",
        languageTitle: "Language",
        languageAr: "العربية",
        languageEn: "English",
        streakTitle: "Streak",
        progressLabel: "Progress",
        streakSubtitle: "Keep up your daily azkar and prayers",
        streakDays: "days",
        goalsTitle: "Today's goals",
        goalMorning: "Morning azkar",
        goalEvening: "Evening azkar",
        goalPrayers: "Five prayers",
        prayerChecklistTitle: "Prayer checklist",
        prayerChecklistNote: "Mark each prayer when completed",
        profileTitle: "Profile",
        profileNote: "Your data is stored locally on this device",
        updateProfile: "Update profile",
        loginSaved: "Profile saved",
        loginRequired: "Please sign in to continue",
        duaAdded: "Duaa added",
        duaDeleted: "Duaa deleted",
        pwaInstall: "App installation started",
        progressTitleMorning: "☀️ Morning Azkar",
        progressTitleEvening: "🌙 Evening Azkar",
        progressTitleSleeping: "🌌 Sleeping Azkar",
        progressTitlePrayer: "🕌 After Prayer Azkar",
        progressText: "Completed",
        progressOf: "of",
        progressAzkar: "azkar",
        resetProgress: "Reset",
        prayerTimesTitle: "🕌 Prayer Times",
        prayerTimesLoading: "Loading prayer times...",
        customTitle: "Your duaas",
        customSubtitle: "Add your favorite duaas and keep them here",
        customPlaceholder: "Type a new duaa...",
        addDua: "Add duaa",
        noDuas: "No duaas yet",
        noDuasHint: "Add your favorite duaas above",
        locationTitle: "Default location",
        cityLabel: "City",
        countryLabel: "Country code",
        appearanceTitle: "Appearance",
        darkOn: "Dark mode on",
        lightOn: "Light mode on",
        aboutTitle: "About",
        offline: "Offline",
        online: "Online",
        offlineNotice: "You are offline — the app still works",
        onlineNotice: "Back online",
        shareCopy: "Copied",
        shareTitle: "Share",
        shareLabel: "Share azkar",
        markComplete: "Mark complete",
        resetCounter: "Reset",
        doneLabel: "Done",
        requiredLabel: "Required",
        benefitShow: "Show benefit and source",
        benefitHide: "Hide benefit and source",
        deleteDua: "Delete duaa",
        scrollTopLabel: "Back to top",
        navLabel: "Main navigation",
        resetAllLabel: "Reset all azkar",
        resetAllToast: "All azkar reset",
        progressResetOne: "Counter reset",
        progressCompleted: "Marked complete",
        meaningTitle: "Meaning and Explanation",
        allComplete: "🎉 Category Complete!"
    }
};
